In [3]:
import os
import pandas as pd
import numpy as np
from collections import Counter

# Plot libraries
import matplotlib.pyplot as plt
import seaborn as sns
color = sns.color_palette()

# Random seed for reproducibility
seed = 202
np.random.seed(seed)

# Ignore warnings
import warnings
warnings.simplefilter('ignore')

# Garbage collector
import gc
gc.enable()

### Import the dataframes

#### Train and test

In [4]:
# Train and test
train_df = pd.read_csv("(1)train.csv")
test_df = pd.read_csv("(1)test.csv")
train_df.shape, test_df.shape

((201917, 6), (123623, 5))

In [5]:
train_df.head()

,first_active_month,card_id,feature_1,feature_2,feature_3,target
0,2017-06-01,C_ID_92a2005557,5,2,1,-0.820283
1,2017-01-01,C_ID_3d0044924f,4,1,0,0.392913
2,2016-08-01,C_ID_d639edf6cd,2,2,0,0.688056
3,2017-09-01,C_ID_186d6a6901,4,3,0,0.142495
4,2017-11-01,C_ID_cdbd2c0db2,1,3,0,-0.159749

#### Transactions

In [6]:
transactions_df = pd.read_csv("(1)transactions.csv")
transactions_df.shape

(30910695, 14)

In [7]:
transactions_df.head()

,authorized_flag,card_id,city_id,category_1,installments,category_3,merchant_category_id,merchant_id,month_lag,purchase_amount,purchase_date,category_2,state_id,subsector_id
0,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_e020e9b302,-8,-0.703331,2017-06-25,1.0,16,37
1,True,C_ID_4e6213e9bc,88,False,0,A,367,M_ID_86ec983688,-7,-0.733128,2017-07-15,1.0,16,16
2,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_979ed661fc,-6,-0.720386,2017-08-09,1.0,16,37
3,True,C_ID_4e6213e9bc,88,False,0,A,560,M_ID_e6d5ae8ea6,-5,-0.735352,2017-09-02,1.0,16,34
4,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_e020e9b302,-11,-0.722865,2017-03-10,1.0,16,37

#### Merchants

In [8]:
merchants_df = pd.read_csv("(1)merchants.csv")
merchants_df.shape

(334620, 22)

In [9]:
merchants_df.head()

,merchant_id,merchant_group_id,merchant_category_id,subsector_id,numerical_1,numerical_2,category_1,most_recent_sales_range,most_recent_purchases_range,avg_sales_lag3,...,avg_sales_lag6,avg_purchases_lag6,active_months_lag6,avg_sales_lag12,avg_purchases_lag12,active_months_lag12,category_4,city_id,state_id,category_2
0,M_ID_838061e48c,8353,792,9,-0.057471,-0.057471,False,E,E,-0.40,...,-2.25,18.666667,6,-2.32,13.916667,12,False,242,9,1.0
1,M_ID_9339d880ad,3184,840,20,-0.057471,-0.057471,False,E,E,-0.72,...,-0.74,1.291667,6,-0.57,1.687500,12,False,22,16,1.0
2,M_ID_e726bbae1e,447,690,1,-0.057471,-0.057471,False,E,E,-82.13,...,-82.13,260.000000,2,-82.13,260.000000,2,False,-1,5,5.0
3,M_ID_c929bb59af,9514,2,20,-0.057471,-0.057471,False,E,E,69667.00,...,69667.00,1.000000,3,69667.00,1.000000,3,False,-1,20,5.0
4,M_ID_dd3ae3de10,30534,278,37,-0.057471,-0.057471,False,E,E,5180.00,...,9830.00,4.166667,6,15826.00,5.600000,10,True,11,23,2.0

In [10]:
#substitute inf values with 2*max_value_in_column
for i in ['3', '6', '12']:
    max_val = max(merchants_df[merchants_df != np.inf]['avg_purchases_lag' + i])
    merchants_df['avg_purchases_lag' + i].replace([np.inf, -np.inf], 2*max_val)

### Transactions and Merchants dataframes merging

In [11]:
print("Number of common merchant_id in merchants_df and transactions_df: %d" % (len(set(transactions_df.merchant_id.unique()).intersection(set(merchants_df.merchant_id.unique())))))
print("merchants_df samples: %d, transactions_df samples: %d" % (merchants_df.shape[0], transactions_df.shape[0]))

Number of common merchant_id in merchants_df and transactions_df: 334620
merchants_df samples: 334620, transactions_df samples: 30910695

In [12]:
for c in merchants_df.columns:
    if c not in transactions_df.columns:
        print(c)

merchant_group_id
numerical_1
numerical_2
most_recent_sales_range
most_recent_purchases_range
avg_sales_lag3
avg_purchases_lag3
active_months_lag3
avg_sales_lag6
avg_purchases_lag6
active_months_lag6
avg_sales_lag12
avg_purchases_lag12
active_months_lag12
category_4

Actually, the only meaningfull features to be merged are merchant_group_id, most_recent_sales_range and most_recent_purchases_range

merchants_df = merchants_df[['merchant_id', "merchant_group_id", "most_recent_sales_range", "most_recent_purchases_range"]]
merchants_df.columns = ['id', "merchant_group_id", "most_recent_sales_range", "most_recent_purchases_range"]
merchants_df.head()

In [13]:
transactions_df = transactions_df.merge(merchants_df, how='left', left_on=['merchant_id', 'city_id', 'category_1', 'category_2', 'merchant_category_id', 'state_id', 'subsector_id'], right_on=['merchant_id', 'city_id', 'category_1', 'category_2', 'merchant_category_id', 'state_id', 'subsector_id'])

In [14]:
len(transactions_df)

30910695

In [15]:
transactions_df.columns

Index(['authorized_flag', 'card_id', 'city_id', 'category_1', 'installments',
       'category_3', 'merchant_category_id', 'merchant_id', 'month_lag',
       'purchase_amount', 'purchase_date', 'category_2', 'state_id',
       'subsector_id', 'merchant_group_id', 'numerical_1', 'numerical_2',
       'most_recent_sales_range', 'most_recent_purchases_range',
       'avg_sales_lag3', 'avg_purchases_lag3', 'active_months_lag3',
       'avg_sales_lag6', 'avg_purchases_lag6', 'active_months_lag6',
       'avg_sales_lag12', 'avg_purchases_lag12', 'active_months_lag12',
       'category_4'],
      dtype='object')

## Merge transactions in train and test

In [22]:
gdf.head()
#gdf = gdf["purchase_amount"].size().reset_index()
#gdf.columns = ["card_id", "num_hist_transactions"]

,authorized_flag,card_id,city_id,category_1,installments,category_3,merchant_category_id,merchant_id,month_lag,purchase_amount,...,avg_sales_lag3,avg_purchases_lag3,active_months_lag3,avg_sales_lag6,avg_purchases_lag6,active_months_lag6,avg_sales_lag12,avg_purchases_lag12,active_months_lag12,category_4
0,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_e020e9b302,-8,-0.703331,...,1.08,1.082451,3.0,1.14,1.114135,6.0,1.19,1.156844,12.0,True
1,True,C_ID_4e6213e9bc,88,False,0,A,367,M_ID_86ec983688,-7,-0.733128,...,1.06,1.052071,3.0,1.06,1.058605,6.0,1.05,1.062087,12.0,True
2,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_979ed661fc,-6,-0.720386,...,0.98,0.974653,3.0,0.98,0.967058,6.0,0.97,0.956668,12.0,True
3,True,C_ID_4e6213e9bc,88,False,0,A,560,M_ID_e6d5ae8ea6,-5,-0.735352,...,1.00,1.053443,3.0,0.88,0.897406,6.0,0.86,0.864394,12.0,True
4,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_e020e9b302,-11,-0.722865,...,1.08,1.082451,3.0,1.14,1.114135,6.0,1.19,1.156844,12.0,True
394,False,C_ID_5037ff576e,322,False,1,B,278,M_ID_b61c7d1be0,-3,-0.595260,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
395,True,C_ID_5037ff576e,138,False,1,B,307,M_ID_fe69229f24,-4,1.189469,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
396,True,C_ID_5037ff576e,138,False,1,B,705,M_ID_efc106141c,-9,-0.640069,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
397,True,C_ID_5037ff576e,226,False,1,B,307,M_ID_708022307c,-4,-0.652256,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
398,True,C_ID_5037ff576e,330,False,1,B,705,M_ID_393b4b8cec,-9,-0.674210,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
512,True,C_ID_0e171c1b48,69,False,0,A,879,M_ID_00a6ca8a8a,-1,-0.728876,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
513,True,C_ID_0e171c1b48,277,False,0,A,703,M_ID_4d6321ce13,-1,-0.662759,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
514,True,C_ID_0e171c1b48,277,False,0,A,683,M_ID_22360595e6,-11,-0.730379,...,1.11,1.160071,3.0,1.13,1.174727,6.0,1.19,1.226067,12.0,True
515,True,C_ID_0e171c1b48,277,False,0,A,561,M_ID_67ead1197d,-3,-0.694315,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
516,False,C_ID_0e171c1b48,277,False,0,A,511,M_ID_0f8e964477,-10,-0.740146,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790,True,C_ID_48fb13e70f,-1,True,1,B,879,M_ID_9139332ccc,-2,-0.649837,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
791,True,C_ID_48fb13e70f,69,False,1,B,560,M_ID_2f6d08eaca,-8,-0.689206,...,1.06,1.033645,3.0,1.03,1.004361,6.0,1.05,1.025078,12.0,True
792,True,C_ID_48fb13e70f,69,False,1,B,544,M_ID_7306a369ea,-8,-0.670378,...,0.96,0.974946,3.0,0.99,0.998318,6.0,1.04,1.023464,12.0,True
793,True,C_ID_48fb13e70f,-1,True,1,B,839,M_ID_50076f761c,-5,-0.596793,...,0.94,0.950611,3.0,0.94,0.930489,6.0,0.84,0.865628,12.0,True
794,True,C_ID_48fb13e70f,69,False,1,B,278,M_ID_f86439cec0,-5,-0.661407,...,1.08,1.092926,3.0,1.09,1.095924,6.0,1.13,1.125829,12.0,True
869,True,C_ID_fc8e41b9cf,69,False,1,B,879,M_ID_00a6ca8a8a,-5,-0.423838,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
870,True,C_ID_fc8e41b9cf,170,False,1,B,367,M_ID_68e26f3cca,-1,-0.728876,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
871,True,C_ID_fc8e41b9cf,69,False,1,B,879,M_ID_00a6ca8a8a,-2,-0.686802,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
872,True,C_ID_fc8e41b9cf,251,False,3,C,126,M_ID_25abfd10aa,-5,-0.070715,...,0.96,1.017007,3.0,1.12,1.299320,6.0,1.27,1.362148,12.0,True
873,True,C_ID_fc8e41b9cf,251,False,1,B,309,M_ID_c2d9240309,-2,-0.719860,...,0.97,0.986310,3.0,1.07,1.007589,6.0,1.11,1.021705,12.0,True
1110,True,C_ID_b02e55aa9d,96,False,0,A,278,M_ID_8894ecfe89,-4,-0.733384,...,4.66,4.214689,3.0,5.47,4.858757,6.0,5.70,4.977401,12.0,False
1111,True,C_ID_b02e55aa9d,283,False,0,A,278,M_ID_cdabc86023,-7,-0.704263,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1112,True,C_ID_b02e55aa9d,283,False,0,A,111,M_ID_1440c83173,-13,-0.717005,...,1.47,1.330033,3.0,1.60,1.413641,6.0,1.60,1.407805,12.0,False
1113,True,C_ID_b02e55aa9d,283,False,0,A,367,M_ID_3339c5faa9,-9,-0.739485,...,1.04,1.031947,3.0,1.02,1.007987,6.0,0.98,0.990977,12.0,False
1114,False,C_ID_b02e55aa9d,283,False,0,A,80,M_ID_3214ef1be2,-9,-0.736765,...,0.98,1.005810,3.0,1.03,1.055963,6.0,1.12,1.151682,12.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30906251,True,C_ID_e9a43776a3,-1,True,2,C,544,M_ID_cdba603e7c,1,-0.577649,...,0.74,0.805316,3.0,0.67,0.728089,6.0,0.63,0.695881,9.0,True
30906369,True,C_ID_942719068e,88,False,0,A,840,M_ID_ca6128f3d8,1,-0.617830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30906392,True,C_ID_7abe7e8632,69,False,1,B,307,M_ID_559180aef0,1,-0.646230,...,1.11,1.098170,3.0,1.03,1.079312,6.0,1.02,1.099972,12.0,True
30906410,True,C_ID_58e7355da2,-1,True,1,B,879,M_ID_9139332ccc,2,-0.734135,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30906448,True,C_ID_a414317bfd,69,False,1,B,302,M_ID_784417e169,1,-0.431351,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30906449,True,C_ID_a414317bfd,179,False,1,B,222,M_ID_7c0fb7f95c,2,-0.475830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30906455,True,C_ID_8468bf25d4,-1,True,1,B,661,M_ID_fc7d7969c3,1,-0.717005,...,0.88,0.890464,3.0,0.72,0.737107,6.0,0.56,0.585596,12.0,True
30907006,True,C_ID_58380a09e1,264,False,1,B,705,M_ID_d3d9c017eb,2,-0.708260,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30907213,True,C_ID_a78baeca00,-1,True,3,C,690,M_ID_3111c6df35,2,-0.146208,...,0.95,0.997999,3.0,0.90,0.967786,6.0,0.79,0.891154,12.0,True
30907226,True,C_ID_0d6f572a45,331,False,1,B,705,M_ID_0e8d93dd86,2,-0.603825,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30907328,True,C_ID_f1fc434f32,331,False,0,A,705,M_ID_77e2942cd8,2,-0.714751,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30907818,True,C_ID_a4bc0c0ad2,140,False,1,B,307,M_ID_a216ec6d06,1,-0.731881,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30907965,True,C_ID_521ababc6e,333,False,1,B,307,M_ID_3beb5cc157,2,-0.566590,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30908033,True,C_ID_354e3e6dc8,251,False,0,A,529,M_ID_8a7841faf9,1,-0.686802,...,0.97,1.107468,3.0,0.79,0.888889,6.0,0.67,0.733607,12.0,True
30908050,True,C_ID_1f5a328c58,117,False,0,A,813,M_ID_b5e8daf772,1,-0.686802,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30908382,True,C_ID_d41fc0f265,69,False,1,B,387,M_ID_1c6d0800e8,1,-0.431351,...,0.96,0.994444,3.0,3.38,1.602778,6.0,2.35,1.326389,12.0,True
30908423,True,C_ID_da78806b00,-1,True,1,B,661,M_ID_fc7d7969c3,2,-0.746893,...,0.88,0.890464,3.0,0.72,0.737107,6.0,0.56,0.585596,12.0,True
30908662,True,C_ID_c295c42f08,-1,True,3,C,879,M_ID_00a6ca8a8a,2,-0.701843,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30908663,True,C_ID_c295c42f08,-1,True,1,B,491,M_ID_79692349d6,1,-0.461855,...,0.95,0.828665,3.0,0.88,0.724008,6.0,0.77,0.619400,12.0,True
30908831,True,C_ID_a0c776add1,-1,True,6,C,806,M_ID_44d0154c81,1,2.512793,...,1.06,1.048276,3.0,1.14,1.021073,6.0,1.01,0.902107,12.0,True
30909365,True,C_ID_f5755ba02c,-1,True,1,B,661,M_ID_fc7d7969c3,1,-0.717005,...,0.88,0.890464,3.0,0.72,0.737107,6.0,0.56,0.585596,12.0,True
30909562,True,C_ID_2495cce89d,-1,True,1,B,879,M_ID_9139332ccc,2,1.777546,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30909638,True,C_ID_cfde762d6f,-1,True,1,B,302,M_ID_b9f9332438,1,2.304706,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30909806,True,C_ID_b31438ec30,244,False,0,A,434,M_ID_f46a6367ca,1,-0.190927,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30909948,True,C_ID_5c9c173cfe,17,False,0,A,705,M_ID_d7d5019c60,1,-0.734887,...,1.08,1.044870,3.0,1.06,1.020381,6.0,1.05,0.978475,10.0,True
30909976,True,C_ID_d18a9d2fe9,-1,True,1,B,661,M_ID_fc7d7969c3,1,-0.745405,...,0.88,0.890464,3.0,0.72,0.737107,6.0,0.56,0.585596,12.0,True
30909977,True,C_ID_d104ec08c4,216,False,0,A,307,M_ID_ef8673e53b,2,-0.439135,...,1.12,1.201715,3.0,1.11,1.260514,6.0,1.04,1.232969,12.0,False
30910032,True,C_ID_e5b7ba41cf,-1,True,1,B,879,M_ID_9139332ccc,1,-0.461434,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30910126,True,C_ID_6d34cb789c,41,False,-1,D,274,M_ID_e2f6434278,1,-0.581616,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30910688,True,C_ID_0509e85404,322,False,1,B,705,M_ID_531bc3b325,2,-0.182166,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

There are a set of duplicated columns (all the couples of the form column_name_x, column_name_y). We can observe that these couples of columns can be merged to obtain a single column with the maximum amount of information. We try to do so for each couple of columns.

In [ ]:
#city_id
#transactions_df['city_id'] = transactions_df['city_id_x']
#transactions_df.drop(labels = ['city_id_x', 'city_id_y'], axis = 1, inplace = True)
#transactions_df.head()

In [ ]:
#category_1

In [ ]:
#merchant_category_id
#transactions_df['merchant_category_id_x'] == transactions_df['merchant_category_id_y']

In [ ]:
#category_2

In [ ]:
#state_id

In [ ]:
#subsector_id

In [17]:
cat_features = ['authorized_flag','city_id', 'category_1','category_3', 'merchant_category_id', 'merchant_id',
                'category_2', 'state_id', 'subsector_id', 'merchant_group_id', 'most_recent_sales_range', 'most_recent_purchases_range', 'category_4']
num_features = ['numerical_1', 'numerical_2','installments', 'month_lag', 'purchase_amount', 'avg_sales_lag3', 'avg_purchases_lag3', 'active_months_lag3',
       'avg_sales_lag6', 'avg_purchases_lag6', 'active_months_lag6', 'avg_sales_lag12', 'avg_purchases_lag12', 'active_months_lag12']

In [ ]:
# OLD
# replace mean of num_features and mode of cat_features
def replace_mean_mode(df, num_features, cat_features):
    new_df = pd.DataFrame(columns = df.columns)
    card_ids_unique = np.unique(df['card_id'])
    
    for card_id in card_ids_unique:
        new_line_num = df.loc[df['card_id'] == card_id][num_features].mean()
        new_line_cat = df.loc[df['card_id'] == card_id][cat_features].mode()
        new_df = new_df.append(pd.concat([new_line_num, new_line_cat], axis=1, join='inner'))
        
    new_df['card_id'] = card_ids_unique
    return new_df

In [ ]:
transactions_df.columns

In [ ]:
#new_transactions_df = replace_mean_mode(transactions_df, num_features, cat_features)

In [25]:
gdf = transactions_df.groupby("card_id")
gdf[num_features].apply(np.mean, result_type = 'reduce')
gdf[cat_features].apply(lambda x: x.mode(), result_type = 'reduce')

TypeError: mean() got an unexpected keyword argument 'result_type'

In [21]:
#new_transactions_df = pd.DataFrame(columns = transactions_df.columns)
#cards_ids_unique = np.unique(gdf['card_id'])

#for name, group in df:
#    gdf[num_features].apply(mean)
#    gdf[cat_features].apply(mode)
#    new_transactions_df = new_transactions_df.append(pd.concat([new_line_num, new_line_cat], axis=1, join='inner'))

#df.groupby('A')['C'].apply(sum)
    
#new_transactions_df['card_id'] = card_ids_unique

In [22]:
gdf.head()

,authorized_flag,card_id,city_id,category_1,installments,category_3,merchant_category_id,merchant_id,month_lag,purchase_amount,...,avg_sales_lag3,avg_purchases_lag3,active_months_lag3,avg_sales_lag6,avg_purchases_lag6,active_months_lag6,avg_sales_lag12,avg_purchases_lag12,active_months_lag12,category_4
0,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_e020e9b302,-8,-0.703331,...,1.08,1.082451,3.0,1.14,1.114135,6.0,1.19,1.156844,12.0,True
1,True,C_ID_4e6213e9bc,88,False,0,A,367,M_ID_86ec983688,-7,-0.733128,...,1.06,1.052071,3.0,1.06,1.058605,6.0,1.05,1.062087,12.0,True
2,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_979ed661fc,-6,-0.720386,...,0.98,0.974653,3.0,0.98,0.967058,6.0,0.97,0.956668,12.0,True
3,True,C_ID_4e6213e9bc,88,False,0,A,560,M_ID_e6d5ae8ea6,-5,-0.735352,...,1.00,1.053443,3.0,0.88,0.897406,6.0,0.86,0.864394,12.0,True
4,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_e020e9b302,-11,-0.722865,...,1.08,1.082451,3.0,1.14,1.114135,6.0,1.19,1.156844,12.0,True
394,False,C_ID_5037ff576e,322,False,1,B,278,M_ID_b61c7d1be0,-3,-0.595260,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
395,True,C_ID_5037ff576e,138,False,1,B,307,M_ID_fe69229f24,-4,1.189469,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
396,True,C_ID_5037ff576e,138,False,1,B,705,M_ID_efc106141c,-9,-0.640069,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
397,True,C_ID_5037ff576e,226,False,1,B,307,M_ID_708022307c,-4,-0.652256,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
398,True,C_ID_5037ff576e,330,False,1,B,705,M_ID_393b4b8cec,-9,-0.674210,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
512,True,C_ID_0e171c1b48,69,False,0,A,879,M_ID_00a6ca8a8a,-1,-0.728876,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
513,True,C_ID_0e171c1b48,277,False,0,A,703,M_ID_4d6321ce13,-1,-0.662759,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
514,True,C_ID_0e171c1b48,277,False,0,A,683,M_ID_22360595e6,-11,-0.730379,...,1.11,1.160071,3.0,1.13,1.174727,6.0,1.19,1.226067,12.0,True
515,True,C_ID_0e171c1b48,277,False,0,A,561,M_ID_67ead1197d,-3,-0.694315,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
516,False,C_ID_0e171c1b48,277,False,0,A,511,M_ID_0f8e964477,-10,-0.740146,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790,True,C_ID_48fb13e70f,-1,True,1,B,879,M_ID_9139332ccc,-2,-0.649837,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
791,True,C_ID_48fb13e70f,69,False,1,B,560,M_ID_2f6d08eaca,-8,-0.689206,...,1.06,1.033645,3.0,1.03,1.004361,6.0,1.05,1.025078,12.0,True
792,True,C_ID_48fb13e70f,69,False,1,B,544,M_ID_7306a369ea,-8,-0.670378,...,0.96,0.974946,3.0,0.99,0.998318,6.0,1.04,1.023464,12.0,True
793,True,C_ID_48fb13e70f,-1,True,1,B,839,M_ID_50076f761c,-5,-0.596793,...,0.94,0.950611,3.0,0.94,0.930489,6.0,0.84,0.865628,12.0,True
794,True,C_ID_48fb13e70f,69,False,1,B,278,M_ID_f86439cec0,-5,-0.661407,...,1.08,1.092926,3.0,1.09,1.095924,6.0,1.13,1.125829,12.0,True
869,True,C_ID_fc8e41b9cf,69,False,1,B,879,M_ID_00a6ca8a8a,-5,-0.423838,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
870,True,C_ID_fc8e41b9cf,170,False,1,B,367,M_ID_68e26f3cca,-1,-0.728876,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
871,True,C_ID_fc8e41b9cf,69,False,1,B,879,M_ID_00a6ca8a8a,-2,-0.686802,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
872,True,C_ID_fc8e41b9cf,251,False,3,C,126,M_ID_25abfd10aa,-5,-0.070715,...,0.96,1.017007,3.0,1.12,1.299320,6.0,1.27,1.362148,12.0,True
873,True,C_ID_fc8e41b9cf,251,False,1,B,309,M_ID_c2d9240309,-2,-0.719860,...,0.97,0.986310,3.0,1.07,1.007589,6.0,1.11,1.021705,12.0,True
1110,True,C_ID_b02e55aa9d,96,False,0,A,278,M_ID_8894ecfe89,-4,-0.733384,...,4.66,4.214689,3.0,5.47,4.858757,6.0,5.70,4.977401,12.0,False
1111,True,C_ID_b02e55aa9d,283,False,0,A,278,M_ID_cdabc86023,-7,-0.704263,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1112,True,C_ID_b02e55aa9d,283,False,0,A,111,M_ID_1440c83173,-13,-0.717005,...,1.47,1.330033,3.0,1.60,1.413641,6.0,1.60,1.407805,12.0,False
1113,True,C_ID_b02e55aa9d,283,False,0,A,367,M_ID_3339c5faa9,-9,-0.739485,...,1.04,1.031947,3.0,1.02,1.007987,6.0,0.98,0.990977,12.0,False
1114,False,C_ID_b02e55aa9d,283,False,0,A,80,M_ID_3214ef1be2,-9,-0.736765,...,0.98,1.005810,3.0,1.03,1.055963,6.0,1.12,1.151682,12.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30906251,True,C_ID_e9a43776a3,-1,True,2,C,544,M_ID_cdba603e7c,1,-0.577649,...,0.74,0.805316,3.0,0.67,0.728089,6.0,0.63,0.695881,9.0,True
30906369,True,C_ID_942719068e,88,False,0,A,840,M_ID_ca6128f3d8,1,-0.617830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30906392,True,C_ID_7abe7e8632,69,False,1,B,307,M_ID_559180aef0,1,-0.646230,...,1.11,1.098170,3.0,1.03,1.079312,6.0,1.02,1.099972,12.0,True
30906410,True,C_ID_58e7355da2,-1,True,1,B,879,M_ID_9139332ccc,2,-0.734135,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30906448,True,C_ID_a414317bfd,69,False,1,B,302,M_ID_784417e169,1,-0.431351,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30906449,True,C_ID_a414317bfd,179,False,1,B,222,M_ID_7c0fb7f95c,2,-0.475830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30906455,True,C_ID_8468bf25d4,-1,True,1,B,661,M_ID_fc7d7969c3,1,-0.717005,...,0.88,0.890464,3.0,0.72,0.737107,6.0,0.56,0.585596,12.0,True
30907006,True,C_ID_58380a09e1,264,False,1,B,705,M_ID_d3d9c017eb,2,-0.708260,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30907213,True,C_ID_a78baeca00,-1,True,3,C,690,M_ID_3111c6df35,2,-0.146208,...,0.95,0.997999,3.0,0.90,0.967786,6.0,0.79,0.891154,12.0,True
30907226,True,C_ID_0d6f572a45,331,False,1,B,705,M_ID_0e8d93dd86,2,-0.603825,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30907328,True,C_ID_f1fc434f32,331,False,0,A,705,M_ID_77e2942cd8,2,-0.714751,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30907818,True,C_ID_a4bc0c0ad2,140,False,1,B,307,M_ID_a216ec6d06,1,-0.731881,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30907965,True,C_ID_521ababc6e,333,False,1,B,307,M_ID_3beb5cc157,2,-0.566590,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30908033,True,C_ID_354e3e6dc8,251,False,0,A,529,M_ID_8a7841faf9,1,-0.686802,...,0.97,1.107468,3.0,0.79,0.888889,6.0,0.67,0.733607,12.0,True
30908050,True,C_ID_1f5a328c58,117,False,0,A,813,M_ID_b5e8daf772,1,-0.686802,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30908382,True,C_ID_d41fc0f265,69,False,1,B,387,M_ID_1c6d0800e8,1,-0.431351,...,0.96,0.994444,3.0,3.38,1.602778,6.0,2.35,1.326389,12.0,True
30908423,True,C_ID_da78806b00,-1,True,1,B,661,M_ID_fc7d7969c3,2,-0.746893,...,0.88,0.890464,3.0,0.72,0.737107,6.0,0.56,0.585596,12.0,True
30908662,True,C_ID_c295c42f08,-1,True,3,C,879,M_ID_00a6ca8a8a,2,-0.701843,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30908663,True,C_ID_c295c42f08,-1,True,1,B,491,M_ID_79692349d6,1,-0.461855,...,0.95,0.828665,3.0,0.88,0.724008,6.0,0.77,0.619400,12.0,True
30908831,True,C_ID_a0c776add1,-1,True,6,C,806,M_ID_44d0154c81,1,2.512793,...,1.06,1.048276,3.0,1.14,1.021073,6.0,1.01,0.902107,12.0,True
30909365,True,C_ID_f5755ba02c,-1,True,1,B,661,M_ID_fc7d7969c3,1,-0.717005,...,0.88,0.890464,3.0,0.72,0.737107,6.0,0.56,0.585596,12.0,True
30909562,True,C_ID_2495cce89d,-1,True,1,B,879,M_ID_9139332ccc,2,1.777546,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30909638,True,C_ID_cfde762d6f,-1,True,1,B,302,M_ID_b9f9332438,1,2.304706,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30909806,True,C_ID_b31438ec30,244,False,0,A,434,M_ID_f46a6367ca,1,-0.190927,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30909948,True,C_ID_5c9c173cfe,17,False,0,A,705,M_ID_d7d5019c60,1,-0.734887,...,1.08,1.044870,3.0,1.06,1.020381,6.0,1.05,0.978475,10.0,True
30909976,True,C_ID_d18a9d2fe9,-1,True,1,B,661,M_ID_fc7d7969c3,1,-0.745405,...,0.88,0.890464,3.0,0.72,0.737107,6.0,0.56,0.585596,12.0,True
30909977,True,C_ID_d104ec08c4,216,False,0,A,307,M_ID_ef8673e53b,2,-0.439135,...,1.12,1.201715,3.0,1.11,1.260514,6.0,1.04,1.232969,12.0,False
30910032,True,C_ID_e5b7ba41cf,-1,True,1,B,879,M_ID_9139332ccc,1,-0.461434,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30910126,True,C_ID_6d34cb789c,41,False,-1,D,274,M_ID_e2f6434278,1,-0.581616,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30910688,True,C_ID_0509e85404,322,False,1,B,705,M_ID_531bc3b325,2,-0.182166,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
gdf.isnull().sum()

AttributeError: Cannot access callable attribute 'isnull' of 'DataFrameGroupBy' objects, try using the 'apply' method

#### Train

In [ ]:
new_train_df = pd.merge(train_df, new_transactions_df, on="card_id", how="left")

In [ ]:
new_train_df.head()

In [ ]:
new_train_df.shape

In [ ]:
new_train_df.isnull().sum()

In [ ]:
new_train_df.drop_duplicates(inplace = True)

In [ ]:
new_train_df.isnull().sum()

In [ ]:
new_train_df.to_csv('(2)small_train.csv', index = False)

#### Test

In [ ]:
new_test_df = pd.join(test, new_transactions_df, on="card_id", how="left")

In [ ]:
new_test_df.head()

In [ ]:
new_test_df.to_csv('(2)small_test.csv', index = False)