In [1]:
import os
import pandas as pd
import numpy as np
from collections import Counter

# Plot libraries
import matplotlib.pyplot as plt
import seaborn as sns
color = sns.color_palette()

# Random seed for reproducibility
seed = 202
np.random.seed(seed)

# Ignore warnings
import warnings
warnings.simplefilter('ignore')

# Garbage collector
import gc
gc.enable()

### Import the dataframes

#### Train and test

In [2]:
# Train and test
train_df = pd.read_csv("(1)train.csv")
test_df = pd.read_csv("(1)test.csv")
train_df.shape, test_df.shape

((201917, 6), (123623, 5))

In [3]:
train_df.head()

,first_active_month,card_id,feature_1,feature_2,feature_3,target
0,2017-06-01,C_ID_92a2005557,5,2,1,-0.820283
1,2017-01-01,C_ID_3d0044924f,4,1,0,0.392913
2,2016-08-01,C_ID_d639edf6cd,2,2,0,0.688056
3,2017-09-01,C_ID_186d6a6901,4,3,0,0.142495
4,2017-11-01,C_ID_cdbd2c0db2,1,3,0,-0.159749

#### Transactions

In [ ]:
transactions_df = pd.read_csv("(1)transactions.csv")
transactions_df.shape

In [ ]:
transactions_df.head()

#### Merchants

In [ ]:
merchants_df = pd.read_csv("(1)merchants.csv")
merchants_df.shape

In [ ]:
merchants_df.head()

In [8]:
"""#substitute inf values with 2*max_value_in_column
for i in ['3', '6', '12']:
    max_val = max(merchants_df[merchants_df != np.inf]['avg_purchases_lag' + i])
    merchants_df['avg_purchases_lag' + i].replace([np.inf, -np.inf], 2*max_val)"""

"#substitute inf values with 2*max_value_in_column\nfor i in ['3', '6', '12']:\n    max_val = max(merchants_df[merchants_df != np.inf]['avg_purchases_lag' + i])\n    merchants_df['avg_purchases_lag' + i].replace([np.inf, -np.inf], 2*max_val)"

### Transactions and Merchants dataframes merging

In [ ]:
print("Number of common merchant_id in merchants_df and transactions_df: %d" % (len(set(transactions_df.merchant_id.unique()).intersection(set(merchants_df.merchant_id.unique())))))
print("merchants_df samples: %d, transactions_df samples: %d" % (merchants_df.shape[0], transactions_df.shape[0]))

In [ ]:
for c in merchants_df.columns:
    if c not in transactions_df.columns:
        print(c)

Actually, the only meaningfull features to be merged are merchant_group_id, most_recent_sales_range and most_recent_purchases_range

In [11]:
# here we can include more features

In [ ]:
merchants_df = merchants_df[['merchant_id', "merchant_group_id", "most_recent_sales_range", "most_recent_purchases_range"]]
merchants_df.columns = ['id', "merchant_group_id", "most_recent_sales_range", "most_recent_purchases_range"]
merchants_df.head()

In [ ]:
trans_merch_df = transactions_df.merge(merchants_df, how='left', left_on='merchant_id', right_on='id')
trans_merch_df = trans_merch_df.drop(['id'], axis=1)
trans_merch_df.shape

In [24]:
trans_merch_df.head(10)

,authorized_flag,card_id,city_id,category_1,installments,category_3,merchant_category_id,merchant_id,month_lag,purchase_amount,purchase_date,category_2,state_id,subsector_id,merchant_group_id,most_recent_sales_range,most_recent_purchases_range
0,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_e020e9b302,-8,-0.703331,2017-06-25,1.0,16,37,35.0,A,A
1,True,C_ID_4e6213e9bc,88,False,0,A,367,M_ID_86ec983688,-7,-0.733128,2017-07-15,1.0,16,16,2084.0,A,A
2,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_979ed661fc,-6,-0.720386,2017-08-09,1.0,16,37,27369.0,C,C
3,True,C_ID_4e6213e9bc,88,False,0,A,560,M_ID_e6d5ae8ea6,-5,-0.735352,2017-09-02,1.0,16,34,24104.0,D,C
4,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_e020e9b302,-11,-0.722865,2017-03-10,1.0,16,37,35.0,A,A
5,True,C_ID_4e6213e9bc,333,False,0,A,80,M_ID_50af771f8d,0,-0.734887,2018-02-24,1.0,9,37,35.0,B,A
6,True,C_ID_4e6213e9bc,88,False,0,A,278,M_ID_5e8220e564,-11,-0.716855,2017-03-21,1.0,16,37,35.0,A,A
7,True,C_ID_4e6213e9bc,3,False,0,A,80,M_ID_9d41786a50,-3,-0.657049,2017-11-18,1.0,16,37,1348.0,C,C
8,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_979ed661fc,-8,-0.737967,2017-06-01,1.0,16,37,27369.0,C,C
9,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_74ba14b5fc,-11,-0.715352,2017-03-16,1.0,16,37,16731.0,D,C

In [15]:
trans_merch_df.isnull().sum()

authorized_flag                   0
card_id                           0
city_id                           0
category_1                        0
installments                      0
category_3                        0
merchant_category_id              0
merchant_id                       0
month_lag                         0
purchase_amount                   0
purchase_date                     0
category_2                        0
state_id                          0
subsector_id                      0
merchant_group_id              9401
most_recent_sales_range        9401
most_recent_purchases_range    9401
dtype: int64

In [16]:
trans_merch_df.dropna(inplace=True)
trans_merch_df.shape

(30901294, 17)

In [25]:
%%time
# This function can be used to compute the mode with groupby()
trans_merch_df.groupby('card_id')['city_id'].apply(lambda x: x.mode())

Wall time: 1min 5s

card_id
C_ID_00007093c1  0    244
C_ID_0001238066  0    314
C_ID_0001506ef0  0    137
C_ID_0001793786  0    179
C_ID_000183fdda  0    161
C_ID_00024e244b  0    156
C_ID_0002709b5a  0    103
C_ID_00027503e2  0    146
C_ID_000298032a  0    233
C_ID_0002ba3c2e  0    344
C_ID_0002c7c2c1  0     69
C_ID_00032df08f  0     69
C_ID_0003754056  0    303
C_ID_000377f6a0  0     76
C_ID_0003be3c83  0    279
C_ID_0003f41435  0      8
C_ID_00042d509c  0     -1
C_ID_0004587331  0     87
C_ID_0004725b87  0    179
C_ID_0004888ddd  0    286
C_ID_0004b68c49  0     69
C_ID_0004c2a5ab  0     -1
C_ID_00057b99fe  0    209
C_ID_000599daf9  0    246
C_ID_0005b2f279  0     79
C_ID_0005b5804f  0     20
C_ID_0005f16cc8  0    244
C_ID_0006152db8  0    117
C_ID_000616f4a8  0    168
C_ID_000664aa02  0    314
                     ...
C_ID_fffb79fb56  0     21
C_ID_fffb9ea3f6  0     76
C_ID_fffba72dc5  0     19
C_ID_fffbdf036b  0     69
C_ID_fffbee5c24  0      4
C_ID_fffc96bf24  0     17
C_ID_fffcb74f49  0    231
C_ID_fffcf66e12  0     57
C_ID_fffd070e0e  0    250
C_ID_fffd1207a8  0     88
C_ID_fffd24dcf3  0     69
C_ID_fffd337484  0     20
C_ID_fffd345048  0    189
C_ID_fffd351e7f  0    107
C_ID_fffd93c8bf  0    280
C_ID_fffd943b91  0     -1
C_ID_fffdad8aa0  0    128
C_ID_fffde15ab6  0    116
C_ID_fffdf34798  0    200
C_ID_fffe29a04a  0     90
C_ID_fffe78b232  0     19
C_ID_fffe866457  0    296
C_ID_fffea6de74  0     87
C_ID_fffeced303  0     -1
C_ID_fffeed3a89  0    143
C_ID_ffff1d9928  0    114
C_ID_ffff579d3a  0     70
C_ID_ffff756266  0    233
C_ID_ffff828181  0     96
C_ID_fffffd5772  0     20
Name: city_id, Length: 329561, dtype: int64

In [18]:
temp = trans_merch_df.groupby("card_id")
gdf = transactions_df.groupby("card_id")
temp

In [76]:
trans_merch_df.groupby("card_id")

In [73]:
prova

## Merge transactions in train and test

In [ ]:
def transaction_merchant_card_id_group(df):
    
    # card_id
    df['transactions_count'] = df.groupby("card_id")['card_id'].count()
    
    # authorized_flag
    df['authorized_transactions_sum'] = df.groupby("card_id")['authorized_flag'].sum()
    df['authorized_transactions_mean'] = df.groupby("card_id")['authorized_flag'].mean()
    # city_id
    df['city_id_nunique'] = df.groupby('card_id')['city_id'].nunique()
    # category_1
    df['category_1_sum'] = df.groupby("card_id")['category_1'].sum()
    df['category_1_mean'] = df.groupby("card_id")['category_1'].mean()
    # installments
    df['installments_nunique'] = df.groupby('card_id')['installments'].nunique()
    df['installments_sum'] = df.groupby('card_id')['installments'].sum()
    df['installments_mean'] = df.groupby('card_id')['installments'].mean()
    df['installments_max'] = df.groupby('card_id')['installments'].max()
    df['installments_min'] = df.groupby('card_id')['installments'].min()
    # category_3
    df['category_3_nunique'] = df.groupby('card_id')['category_3'].nunique()
    # merchant_category_id
    df['merchant_category_id_nunique'] = df.groupby('card_id')['merchant_category_id'].nunique()    
    # merchant_id
    df['merchant_id_nunique'] = df.groupby('card_id')['merchant_id'].nunique()    
    # month_lag
    df['month_lag_nunique'] = df.groupby('card_id')['month_lag'].nunique()
    df['month_lag_sum'] = df.groupby('card_id')['month_lag'].sum()
    df['month_lag_mean'] = df.groupby('card_id')['month_lag'].mean()
    df['month_lag_max'] = df.groupby('card_id')['month_lag'].max()
    df['month_lag_min'] = df.groupby('card_id')['month_lag'].min()
    # purchase_amount
    df['month_lag_nunique'] = df.groupby('card_id')['month_lag'].nunique()
    df['month_lag_sum'] = df.groupby('card_id')['month_lag'].sum()
    df['month_lag_mean'] = df.groupby('card_id')['month_lag'].mean()
    df['month_lag_max'] = df.groupby('card_id')['month_lag'].max()
    df['month_lag_min'] = df.groupby('card_id')['month_lag'].min()
    # purchase_date
    # NOTE: This must be replaced with datetime time steps
    df['purchase_date_nunique'] = df.groupby('card_id')['purchase_date'].nunique()
    # category_2
    df['category_2_nunique'] = df.groupby('card_id')['category_2'].nunique()
    # state_id
    df['state_id_nunique'] = df.groupby('card_id')['state_id'].nunique()
    # subsector_id
    df['subsector_id_nunique'] = df.groupby('card_id')['subsector_id'].nunique()
    # merchant_group_id
    df['merchant_group_id_nunique'] = df.groupby('card_id')['merchant_group_id'].nunique()
    # most_recent_sales_range
    df['most_recent_sales_range_nunique'] = df.groupby('card_id')['most_recent_sales_range'].nunique()
    # most_recent_purchases_range
    df['most_recent_purchases_range_nunique'] = df.groupby('card_id')['most_recent_purchases_range'].nunique()
    
    return df

In [19]:
gdf = transactions_df.groupby("card_id")
gdf.head()

,authorized_flag,card_id,city_id,category_1,installments,category_3,merchant_category_id,merchant_id,month_lag,purchase_amount,purchase_date,category_2,state_id,subsector_id
0,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_e020e9b302,-8,-0.703331,2017-06-25,1.0,16,37
1,True,C_ID_4e6213e9bc,88,False,0,A,367,M_ID_86ec983688,-7,-0.733128,2017-07-15,1.0,16,16
2,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_979ed661fc,-6,-0.720386,2017-08-09,1.0,16,37
3,True,C_ID_4e6213e9bc,88,False,0,A,560,M_ID_e6d5ae8ea6,-5,-0.735352,2017-09-02,1.0,16,34
4,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_e020e9b302,-11,-0.722865,2017-03-10,1.0,16,37
394,False,C_ID_5037ff576e,322,False,1,B,278,M_ID_b61c7d1be0,-3,-0.595260,2017-09-07,3.0,11,37
395,True,C_ID_5037ff576e,138,False,1,B,307,M_ID_fe69229f24,-4,1.189469,2017-08-14,1.0,15,19
396,True,C_ID_5037ff576e,138,False,1,B,705,M_ID_efc106141c,-9,-0.640069,2017-03-05,1.0,15,33
397,True,C_ID_5037ff576e,226,False,1,B,307,M_ID_708022307c,-4,-0.652256,2017-08-15,1.0,16,19
398,True,C_ID_5037ff576e,330,False,1,B,705,M_ID_393b4b8cec,-9,-0.674210,2017-03-26,3.0,17,33
512,True,C_ID_0e171c1b48,69,False,0,A,879,M_ID_00a6ca8a8a,-1,-0.728876,2018-01-05,1.0,9,29
513,True,C_ID_0e171c1b48,277,False,0,A,703,M_ID_4d6321ce13,-1,-0.662759,2018-01-27,4.0,13,29
514,True,C_ID_0e171c1b48,277,False,0,A,683,M_ID_22360595e6,-11,-0.730379,2017-03-15,4.0,13,34
515,True,C_ID_0e171c1b48,277,False,0,A,561,M_ID_67ead1197d,-3,-0.694315,2017-11-17,4.0,13,7
516,False,C_ID_0e171c1b48,277,False,0,A,511,M_ID_0f8e964477,-10,-0.740146,2017-04-12,4.0,13,7
790,True,C_ID_48fb13e70f,-1,True,1,B,879,M_ID_9139332ccc,-2,-0.649837,2017-12-09,6.0,-1,29
791,True,C_ID_48fb13e70f,69,False,1,B,560,M_ID_2f6d08eaca,-8,-0.689206,2017-06-06,1.0,9,34
792,True,C_ID_48fb13e70f,69,False,1,B,544,M_ID_7306a369ea,-8,-0.670378,2017-06-21,1.0,9,29
793,True,C_ID_48fb13e70f,-1,True,1,B,839,M_ID_50076f761c,-5,-0.596793,2017-09-21,6.0,-1,29
794,True,C_ID_48fb13e70f,69,False,1,B,278,M_ID_f86439cec0,-5,-0.661407,2017-09-14,1.0,9,37
869,True,C_ID_fc8e41b9cf,69,False,1,B,879,M_ID_00a6ca8a8a,-5,-0.423838,2017-09-14,1.0,9,29
870,True,C_ID_fc8e41b9cf,170,False,1,B,367,M_ID_68e26f3cca,-1,-0.728876,2018-01-20,3.0,8,16
871,True,C_ID_fc8e41b9cf,69,False,1,B,879,M_ID_00a6ca8a8a,-2,-0.686802,2017-12-15,1.0,9,29
872,True,C_ID_fc8e41b9cf,251,False,3,C,126,M_ID_25abfd10aa,-5,-0.070715,2017-09-28,3.0,8,27
873,True,C_ID_fc8e41b9cf,251,False,1,B,309,M_ID_c2d9240309,-2,-0.719860,2017-12-15,3.0,8,21
1110,True,C_ID_b02e55aa9d,96,False,0,A,278,M_ID_8894ecfe89,-4,-0.733384,2017-10-05,1.0,9,37
1111,True,C_ID_b02e55aa9d,283,False,0,A,278,M_ID_cdabc86023,-7,-0.704263,2017-07-01,1.0,9,37
1112,True,C_ID_b02e55aa9d,283,False,0,A,111,M_ID_1440c83173,-13,-0.717005,2017-01-07,1.0,9,36
1113,True,C_ID_b02e55aa9d,283,False,0,A,367,M_ID_3339c5faa9,-9,-0.739485,2017-05-01,1.0,9,16
1114,False,C_ID_b02e55aa9d,283,False,0,A,80,M_ID_3214ef1be2,-9,-0.736765,2017-05-14,1.0,9,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30906251,True,C_ID_e9a43776a3,-1,True,2,C,544,M_ID_cdba603e7c,1,-0.577649,2017-12-15,6.0,-1,29
30906369,True,C_ID_942719068e,88,False,0,A,840,M_ID_ca6128f3d8,1,-0.617830,2018-01-10,1.0,16,20
30906392,True,C_ID_7abe7e8632,69,False,1,B,307,M_ID_559180aef0,1,-0.646230,2018-03-10,1.0,9,19
30906410,True,C_ID_58e7355da2,-1,True,1,B,879,M_ID_9139332ccc,2,-0.734135,2017-10-30,6.0,-1,29
30906448,True,C_ID_a414317bfd,69,False,1,B,302,M_ID_784417e169,1,-0.431351,2018-03-12,1.0,9,22
30906449,True,C_ID_a414317bfd,179,False,1,B,222,M_ID_7c0fb7f95c,2,-0.475830,2018-04-19,6.0,-1,21
30906455,True,C_ID_8468bf25d4,-1,True,1,B,661,M_ID_fc7d7969c3,1,-0.717005,2018-03-29,6.0,-1,8
30907006,True,C_ID_58380a09e1,264,False,1,B,705,M_ID_d3d9c017eb,2,-0.708260,2018-04-24,2.0,18,33
30907213,True,C_ID_a78baeca00,-1,True,3,C,690,M_ID_3111c6df35,2,-0.146208,2018-04-18,6.0,-1,1
30907226,True,C_ID_0d6f572a45,331,False,1,B,705,M_ID_0e8d93dd86,2,-0.603825,2018-04-27,1.0,16,33
30907328,True,C_ID_f1fc434f32,331,False,0,A,705,M_ID_77e2942cd8,2,-0.714751,2018-04-04,1.0,16,33
30907818,True,C_ID_a4bc0c0ad2,140,False,1,B,307,M_ID_a216ec6d06,1,-0.731881,2018-03-28,1.0,9,19
30907965,True,C_ID_521ababc6e,333,False,1,B,307,M_ID_3beb5cc157,2,-0.566590,2018-04-10,1.0,9,19
30908033,True,C_ID_354e3e6dc8,251,False,0,A,529,M_ID_8a7841faf9,1,-0.686802,2018-03-26,3.0,8,20
30908050,True,C_ID_1f5a328c58,117,False,0,A,813,M_ID_b5e8daf772,1,-0.686802,2018-03-05,4.0,13,29
30908382,True,C_ID_d41fc0f265,69,False,1,B,387,M_ID_1c6d0800e8,1,-0.431351,2018-01-29,1.0,9,36
30908423,True,C_ID_da78806b00,-1,True,1,B,661,M_ID_fc7d7969c3,2,-0.746893,2018-03-11,6.0,-1,8
30908662,True,C_ID_c295c42f08,-1,True,3,C,879,M_ID_00a6ca8a8a,2,-0.701843,2017-10-07,6.0,-1,29
30908663,True,C_ID_c295c42f08,-1,True,1,B,491,M_ID_79692349d6,1,-0.461855,2017-09-03,6.0,-1,3
30908831,True,C_ID_a0c776add1,-1,True,6,C,806,M_ID_44d0154c81,1,2.512793,2018-02-10,6.0,-1,9
30909365,True,C_ID_f5755ba02c,-1,True,1,B,661,M_ID_fc7d7969c3,1,-0.717005,2018-03-29,6.0,-1,8
30909562,True,C_ID_2495cce89d,-1,True,1,B,879,M_ID_9139332ccc,2,1.777546,2018-03-13,6.0,-1,29
30909638,True,C_ID_cfde762d6f,-1,True,1,B,302,M_ID_b9f9332438,1,2.304706,2018-03-11,6.0,-1,22
30909806,True,C_ID_b31438ec30,244,False,0,A,434,M_ID_f46a6367ca,1,-0.190927,2017-10-07,3.0,2,32
30909948,True,C_ID_5c9c173cfe,17,False,0,A,705,M_ID_d7d5019c60,1,-0.734887,2018-03-21,4.0,22,33
30909976,True,C_ID_d18a9d2fe9,-1,True,1,B,661,M_ID_fc7d7969c3,1,-0.745405,2018-03-09,6.0,-1,8
30909977,True,C_ID_d104ec08c4,216,False,0,A,307,M_ID_ef8673e53b,2,-0.439135,2018-04-12,5.0,20,19
30910032,True,C_ID_e5b7ba41cf,-1,True,1,B,879,M_ID_9139332ccc,1,-0.461434,2018-02-09,6.0,-1,29
30910126,True,C_ID_6d34cb789c,41,False,-1,D,274,M_ID_e2f6434278,1,-0.581616,2018-03-24,5.0,20,36
30910688,True,C_ID_0509e85404,322,False,1,B,705,M_ID_531bc3b325,2,-0.182166,2018-04-30,3.0,11,33

In [ ]:
aggs = {}
for col in ['month','hour','weekofyear','dayofweek','year','subsector_id','merchant_id','merchant_category_id']:
    aggs[col] = ['nunique']
aggs['purchase_amount'] = ['sum','max','min','mean','var']
aggs['installments'] = ['sum','max','min','mean','var']
aggs['purchase_date'] = ['max','min']
aggs['month_lag'] = ['max','min','mean','var']
aggs['month_diff'] = ['mean']
aggs['weekend'] = ['sum', 'mean']
aggs['category_1'] = ['sum', 'mean']
aggs['card_id'] = ['size']

for col in ['category_2','category_3']:
    new_merchant_trans[col+'_mean'] = new_merchant_trans.groupby([col])['purchase_amount'].transform('mean')
    aggs[col+'_mean'] = ['mean']
    
new_columns = get_new_columns('new_hist',aggs)
hist_trans_group = new_merchant_trans.groupby('card_id').agg(aggs)
hist_trans_group.columns = new_columns
hist_trans_group.reset_index(drop=False,inplace=True)
hist_trans_group['new_hist_purchase_date_diff'] = (hist_trans_group['new_hist_purchase_date_max'] - hist_trans_group['new_hist_purchase_date_min']).dt.days
hist_trans_group['new_hist_purchase_date_average'] = hist_trans_group['new_hist_purchase_date_diff']/hist_trans_group['new_hist_card_id_size']
hist_trans_group['new_hist_purchase_date_uptonow'] = (datetime.datetime.today() - hist_trans_group['new_hist_purchase_date_max']).dt.days
train = train.merge(hist_trans_group,on='card_id',how='left')
test = test.merge(hist_trans_group,on='card_id',how='left')

In [16]:
gdf = transactions_df.groupby("card_id")
gdf.head()
#gdf = gdf["purchase_amount"].size().reset_index()
#gdf.columns = ["card_id", "num_hist_transactions"]

,authorized_flag,card_id,city_id,category_1,installments,category_3,merchant_category_id,merchant_id,month_lag,purchase_amount,purchase_date,category_2,state_id,subsector_id
0,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_e020e9b302,-8,-0.703331,2017-06-25,1.0,16,37
1,True,C_ID_4e6213e9bc,88,False,0,A,367,M_ID_86ec983688,-7,-0.733128,2017-07-15,1.0,16,16
2,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_979ed661fc,-6,-0.720386,2017-08-09,1.0,16,37
3,True,C_ID_4e6213e9bc,88,False,0,A,560,M_ID_e6d5ae8ea6,-5,-0.735352,2017-09-02,1.0,16,34
4,True,C_ID_4e6213e9bc,88,False,0,A,80,M_ID_e020e9b302,-11,-0.722865,2017-03-10,1.0,16,37
394,False,C_ID_5037ff576e,322,False,1,B,278,M_ID_b61c7d1be0,-3,-0.595260,2017-09-07,3.0,11,37
395,True,C_ID_5037ff576e,138,False,1,B,307,M_ID_fe69229f24,-4,1.189469,2017-08-14,1.0,15,19
396,True,C_ID_5037ff576e,138,False,1,B,705,M_ID_efc106141c,-9,-0.640069,2017-03-05,1.0,15,33
397,True,C_ID_5037ff576e,226,False,1,B,307,M_ID_708022307c,-4,-0.652256,2017-08-15,1.0,16,19
398,True,C_ID_5037ff576e,330,False,1,B,705,M_ID_393b4b8cec,-9,-0.674210,2017-03-26,3.0,17,33
512,True,C_ID_0e171c1b48,69,False,0,A,879,M_ID_00a6ca8a8a,-1,-0.728876,2018-01-05,1.0,9,29
513,True,C_ID_0e171c1b48,277,False,0,A,703,M_ID_4d6321ce13,-1,-0.662759,2018-01-27,4.0,13,29
514,True,C_ID_0e171c1b48,277,False,0,A,683,M_ID_22360595e6,-11,-0.730379,2017-03-15,4.0,13,34
515,True,C_ID_0e171c1b48,277,False,0,A,561,M_ID_67ead1197d,-3,-0.694315,2017-11-17,4.0,13,7
516,False,C_ID_0e171c1b48,277,False,0,A,511,M_ID_0f8e964477,-10,-0.740146,2017-04-12,4.0,13,7
790,True,C_ID_48fb13e70f,-1,True,1,B,879,M_ID_9139332ccc,-2,-0.649837,2017-12-09,6.0,-1,29
791,True,C_ID_48fb13e70f,69,False,1,B,560,M_ID_2f6d08eaca,-8,-0.689206,2017-06-06,1.0,9,34
792,True,C_ID_48fb13e70f,69,False,1,B,544,M_ID_7306a369ea,-8,-0.670378,2017-06-21,1.0,9,29
793,True,C_ID_48fb13e70f,-1,True,1,B,839,M_ID_50076f761c,-5,-0.596793,2017-09-21,6.0,-1,29
794,True,C_ID_48fb13e70f,69,False,1,B,278,M_ID_f86439cec0,-5,-0.661407,2017-09-14,1.0,9,37
869,True,C_ID_fc8e41b9cf,69,False,1,B,879,M_ID_00a6ca8a8a,-5,-0.423838,2017-09-14,1.0,9,29
870,True,C_ID_fc8e41b9cf,170,False,1,B,367,M_ID_68e26f3cca,-1,-0.728876,2018-01-20,3.0,8,16
871,True,C_ID_fc8e41b9cf,69,False,1,B,879,M_ID_00a6ca8a8a,-2,-0.686802,2017-12-15,1.0,9,29
872,True,C_ID_fc8e41b9cf,251,False,3,C,126,M_ID_25abfd10aa,-5,-0.070715,2017-09-28,3.0,8,27
873,True,C_ID_fc8e41b9cf,251,False,1,B,309,M_ID_c2d9240309,-2,-0.719860,2017-12-15,3.0,8,21
1110,True,C_ID_b02e55aa9d,96,False,0,A,278,M_ID_8894ecfe89,-4,-0.733384,2017-10-05,1.0,9,37
1111,True,C_ID_b02e55aa9d,283,False,0,A,278,M_ID_cdabc86023,-7,-0.704263,2017-07-01,1.0,9,37
1112,True,C_ID_b02e55aa9d,283,False,0,A,111,M_ID_1440c83173,-13,-0.717005,2017-01-07,1.0,9,36
1113,True,C_ID_b02e55aa9d,283,False,0,A,367,M_ID_3339c5faa9,-9,-0.739485,2017-05-01,1.0,9,16
1114,False,C_ID_b02e55aa9d,283,False,0,A,80,M_ID_3214ef1be2,-9,-0.736765,2017-05-14,1.0,9,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30906251,True,C_ID_e9a43776a3,-1,True,2,C,544,M_ID_cdba603e7c,1,-0.577649,2017-12-15,6.0,-1,29
30906369,True,C_ID_942719068e,88,False,0,A,840,M_ID_ca6128f3d8,1,-0.617830,2018-01-10,1.0,16,20
30906392,True,C_ID_7abe7e8632,69,False,1,B,307,M_ID_559180aef0,1,-0.646230,2018-03-10,1.0,9,19
30906410,True,C_ID_58e7355da2,-1,True,1,B,879,M_ID_9139332ccc,2,-0.734135,2017-10-30,6.0,-1,29
30906448,True,C_ID_a414317bfd,69,False,1,B,302,M_ID_784417e169,1,-0.431351,2018-03-12,1.0,9,22
30906449,True,C_ID_a414317bfd,179,False,1,B,222,M_ID_7c0fb7f95c,2,-0.475830,2018-04-19,6.0,-1,21
30906455,True,C_ID_8468bf25d4,-1,True,1,B,661,M_ID_fc7d7969c3,1,-0.717005,2018-03-29,6.0,-1,8
30907006,True,C_ID_58380a09e1,264,False,1,B,705,M_ID_d3d9c017eb,2,-0.708260,2018-04-24,2.0,18,33
30907213,True,C_ID_a78baeca00,-1,True,3,C,690,M_ID_3111c6df35,2,-0.146208,2018-04-18,6.0,-1,1
30907226,True,C_ID_0d6f572a45,331,False,1,B,705,M_ID_0e8d93dd86,2,-0.603825,2018-04-27,1.0,16,33
30907328,True,C_ID_f1fc434f32,331,False,0,A,705,M_ID_77e2942cd8,2,-0.714751,2018-04-04,1.0,16,33
30907818,True,C_ID_a4bc0c0ad2,140,False,1,B,307,M_ID_a216ec6d06,1,-0.731881,2018-03-28,1.0,9,19
30907965,True,C_ID_521ababc6e,333,False,1,B,307,M_ID_3beb5cc157,2,-0.566590,2018-04-10,1.0,9,19
30908033,True,C_ID_354e3e6dc8,251,False,0,A,529,M_ID_8a7841faf9,1,-0.686802,2018-03-26,3.0,8,20
30908050,True,C_ID_1f5a328c58,117,False,0,A,813,M_ID_b5e8daf772,1,-0.686802,2018-03-05,4.0,13,29
30908382,True,C_ID_d41fc0f265,69,False,1,B,387,M_ID_1c6d0800e8,1,-0.431351,2018-01-29,1.0,9,36
30908423,True,C_ID_da78806b00,-1,True,1,B,661,M_ID_fc7d7969c3,2,-0.746893,2018-03-11,6.0,-1,8
30908662,True,C_ID_c295c42f08,-1,True,3,C,879,M_ID_00a6ca8a8a,2,-0.701843,2017-10-07,6.0,-1,29
30908663,True,C_ID_c295c42f08,-1,True,1,B,491,M_ID_79692349d6,1,-0.461855,2017-09-03,6.0,-1,3
30908831,True,C_ID_a0c776add1,-1,True,6,C,806,M_ID_44d0154c81,1,2.512793,2018-02-10,6.0,-1,9
30909365,True,C_ID_f5755ba02c,-1,True,1,B,661,M_ID_fc7d7969c3,1,-0.717005,2018-03-29,6.0,-1,8
30909562,True,C_ID_2495cce89d,-1,True,1,B,879,M_ID_9139332ccc,2,1.777546,2018-03-13,6.0,-1,29
30909638,True,C_ID_cfde762d6f,-1,True,1,B,302,M_ID_b9f9332438,1,2.304706,2018-03-11,6.0,-1,22
30909806,True,C_ID_b31438ec30,244,False,0,A,434,M_ID_f46a6367ca,1,-0.190927,2017-10-07,3.0,2,32
30909948,True,C_ID_5c9c173cfe,17,False,0,A,705,M_ID_d7d5019c60,1,-0.734887,2018-03-21,4.0,22,33
30909976,True,C_ID_d18a9d2fe9,-1,True,1,B,661,M_ID_fc7d7969c3,1,-0.745405,2018-03-09,6.0,-1,8
30909977,True,C_ID_d104ec08c4,216,False,0,A,307,M_ID_ef8673e53b,2,-0.439135,2018-04-12,5.0,20,19
30910032,True,C_ID_e5b7ba41cf,-1,True,1,B,879,M_ID_9139332ccc,1,-0.461434,2018-02-09,6.0,-1,29
30910126,True,C_ID_6d34cb789c,41,False,-1,D,274,M_ID_e2f6434278,1,-0.581616,2018-03-24,5.0,20,36
30910688,True,C_ID_0509e85404,322,False,1,B,705,M_ID_531bc3b325,2,-0.182166,2018-04-30,3.0,11,33

There are a set of duplicated columns (all the couples of the form column_name_x, column_name_y). We can observe that these couples of columns can be merged to obtain a single column with the maximum amount of information. We try to do so for each couple of columns.

In [ ]:
#city_id
#transactions_df['city_id'] = transactions_df['city_id_x']
#transactions_df.drop(labels = ['city_id_x', 'city_id_y'], axis = 1, inplace = True)
#transactions_df.head()

In [ ]:
#category_1

In [ ]:
#merchant_category_id
#transactions_df['merchant_category_id_x'] == transactions_df['merchant_category_id_y']

In [ ]:
#category_2

In [ ]:
#state_id

In [ ]:
#subsector_id

In [23]:
cat_features = ['authorized_flag','city_id', 'category_1','category_3', 'merchant_category_id', 'merchant_id',
                'category_2', 'state_id', 'subsector_id', 'merchant_group_id', 'most_recent_sales_range', 'most_recent_purchases_range', 'category_4']
num_features = ['numerical_1', 'numerical_2','installments', 'month_lag', 'purchase_amount', 'avg_sales_lag3', 'avg_purchases_lag3', 'active_months_lag3',
       'avg_sales_lag6', 'avg_purchases_lag6', 'active_months_lag6', 'avg_sales_lag12', 'avg_purchases_lag12', 'active_months_lag12']

In [ ]:
# OLD
# replace mean of num_features and mode of cat_features
def replace_mean_mode(df, num_features, cat_features):
    new_df = pd.DataFrame(columns = df.columns)
    card_ids_unique = np.unique(df['card_id'])
    
    for card_id in card_ids_unique:
        new_line_num = df.loc[df['card_id'] == card_id][num_features].mean()
        new_line_cat = df.loc[df['card_id'] == card_id][cat_features].mode()
        new_df = new_df.append(pd.concat([new_line_num, new_line_cat], axis=1, join='inner'))
        
    new_df['card_id'] = card_ids_unique
    return new_df

In [ ]:
transactions_df.columns

In [ ]:
#new_transactions_df = replace_mean_mode(transactions_df, num_features, cat_features)

In [2]:
new_transactions_df = pd.DataFrame(columns = transactions_df.columns)
cards_ids_unique = np.unique(gdf['card_id'])

for name, group in df:
    new_line_num = group[num_features].mean()
    new_line_cat = group[cat_features].mode()
    new_transactions_df = new_transactions_df.append(pd.concat([new_line_num, new_line_cat], axis=1, join='inner'))
    
new_transactions_df['card_id'] = card_ids_unique

NameError: name 'pd' is not defined

In [1]:
new_transactions_df.head()

NameError: name 'new_transactions_df' is not defined

#### Train

In [ ]:
new_train_df = pd.merge(train_df, new_transactions_df, on="card_id", how="left")

In [ ]:
new_train_df.head()

In [ ]:
new_train_df.shape

In [ ]:
new_train_df.isnull().sum()

In [ ]:
new_train_df.drop_duplicates(inplace = True)

In [ ]:
new_train_df.isnull().sum()

In [ ]:
new_train_df.to_csv('(2)small_train.csv', index = False)

#### Test

In [ ]:
new_test_df = pd.join(test, new_transactions_df, on="card_id", how="left")

In [ ]:
new_test_df.head()

In [ ]:
new_test_df.to_csv('(2)small_test.csv', index = False)